name: Continuous Integration
on: 
  push:
    paths-ignore:
      - 'documentation/**'
      - 'README.md'
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --target test --tag my-test-image .
    - run: docker run --env-file .env.test my-test-image


    - run: docker build --target production --tag todo-app:prod .
    - run: docker run -p 8000:8000 --env-file .env todo-app:prod --tag production
    - run: docker login --username markrobertdunn --85c6da34-27b9-4012-a95b-eca05b3a56e1 
    - run: docker push todo-app:prod