name: Continuous Integration
on: 
  push:
    paths-ignore:
      - 'documentation/**'
      - 'README.md'
  pull_request:

jobs:
  Test_Build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build test image
      run: docker build --target test --tag my-test-image .

    - name: Run tests
      run: docker run --env-file .env.test my-test-image



  Production_Build:
    name: Build and Publish
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/exercise-8' }}
    runs-on: ubuntu-latest    
    needs: Test_Build

    steps:
      - uses: actions/checkout@v2
        
      - name: Build Production Image
        run: docker build --target production --tag markrobertdunn/todo-app:$GITHUB_SHA .

      - name: Login to Docker
        run: docker login --username markrobertdunn --password ${{ secrets.DOCKERHUBKEY }}

      - name: Publish Production Image to Docker
        run: docker push markrobertdunn/todo-app:$GITHUB_SHA

  Production_Release:
    name: Build and Release
    needs: Production_Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}            
          heroku_app_name: devops-todoapp
          env_file: .env
        env:
          FLASK_APP: todo_app/app
          FLASK_ENV: development
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          TOKEN: ${{secrets.TOKEN}}
          BOARD_ID: 61b77a51327f31334159a742
          TO_DO: 61b77a51327f31334159a743
          DOING: 61b77a51327f31334159a744
          DONE: 61b77a51327f31334159a745